# .github/workflows/restart-railway.yml
name: Restart Railway on Config Update

on:
  push:
    branches:
      - main

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Call Railway API
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
            https://backboard.railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/redeploy
